# Configs for pwills.com

title: "jspenced.github.io"
name: "Jeff Spencer"
email: jeffspencerd@gmail.com
url: "https://jspenced.github.io/"
repository: "JSpenced/JSpenced.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Jeff Spencer"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I enjoy  using computers and math to find new ways to look at data to solve complex problems."
  location: "Toronto, CA"
  github : JSpenced
  linkedin: JSpenced
  email  : jeffspencerd@gmail.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "jspenced"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-160636910-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
